"""Multilevel costly signaling framework for monumental architecture."""

# Layer 3 alternative network forms (robustness analysis)
from signaling.layer3 import (
    NetworkDegreeSpec,
    between_group_lambda_diagnostics,
    calibrate_alternative_network_forms,
    network_degree_exponential,
    network_degree_exponential_derivative,
    network_degree_hill,
    network_degree_hill_derivative,
    network_degree_piecewise,
    network_degree_piecewise_derivative,
)

# Layer 1: Individual signaling equilibrium
from signaling.layer1 import (
    BenefitSpec,
    CostSpec,
    EquilibriumResult,
    FitnessResult,
    SpenceResult,
    benefit_function_sensitivity,
    concave_benefit,
    average_equilibrium_cost,
    cost_at_equilibrium,
    cost_function_sensitivity,
    lambda_W_for_C,
    mean_payoff_multiplier,
    derive_aggregate_signal,
    derive_equilibrium,
    derive_equilibrium_fitness,
    equilibrium_fitness,
    equilibrium_investment,
    expected_monument_stock,
    exponential_cost,
    fitness_gain,
    group_monument_stock,
    linear_benefit,
    power_cost,
    quadratic_cost,
    verify_spence_condition,
    # Layer 1 deviation/pooling analysis
    expected_fitness_gain,
    fitness_at_deviation,
    free_rider_deterrent,
    participation_differential_sampled,
    participation_equilibrium,
    pooling_fitness,
    receiver_inference,
    # Channel selection analysis
    ALL_CHANNELS,
    FEAST_CHANNEL,
    HUNTING_CHANNEL,
    MONUMENT_CHANNEL,
    RITUAL_CHANNEL,
    SignalChannel,
    VERBAL_CHANNEL,
    channel_dominance_condition,
    channel_effective_lambda,
    incremental_lambda,
    lambda_decomposition,
    monument_dominance_threshold,
    signal_fidelity,
)

# Layer 2: Intergroup assessment and conflict resolution
from signaling.layer2 import (
    bourgeois_conflict_prob,
    calibrate_conflict_reduction,
    compare_assessment_models,
    constrained_sigma_0,
    derived_conflict_reduction,
    derived_conflict_reduction_self_assessment,
    effective_noise,
    mutual_assessment_conflict_prob,
    mutual_assessment_exponential,
    self_assessment_conflict_prob,
    war_of_attrition_cost,
    war_of_attrition_deterrence,
)

# Calibration parameters
from signaling.calibration import (
    COMPETITION,
    PLACEMENT,
    CALIBRATION_TARGETS,
    DEFAULT_ALPHA_CONFLICT,
    DEFAULT_BETA_CONFLICT,
    DEFAULT_C_RATE,
    DEFAULT_D,
    DEFAULT_KAPPA,
    DEFAULT_LAMBDA,
    DEFAULT_LAMBDA_W_ANCHOR,
    DEFAULT_LAM_C,
    DEFAULT_LAM_W,
    DEFAULT_LAM_X,
    DEFAULT_M_OWN,
    DEFAULT_M_SCALE,
    DEFAULT_M_THRESH,
    DEFAULT_N,
    DEFAULT_N_COMPUTE,
    DEFAULT_P_BASE,
    DEFAULT_Q_MAX,
    DEFAULT_Q_MIN,
    DEFAULT_RHO_FEAST,
    DEFAULT_RHO_HUNTING,
    DEFAULT_RHO_MONUMENT,
    DEFAULT_RHO_RITUAL,
    DEFAULT_RHO_VERBAL,
    DEFAULT_SIGMA_0,
    DEFAULT_STEEPNESS,
    DEFAULT_T_0,
    DEFAULT_V,
    DEFAULT_WINDFALL_PROB,
    INITIAL_MODEL_PARAMS,
    RAPA_ITI,
    RAPA_NUI,
)

# Price equation: sensitivity analysis
from signaling.price_equation import (
    sensitivity_tornado,
    sigma_star_self_consistent,
    sigma_star_vs_param,
    stability_analysis,
    stability_analysis_self_consistent,
    # Full multilevel Price partition (positional within-group reward)
    within_group_status_differential,
    mixed_group_mean_fitness,
    within_group_regression,
    between_group_regression,
    emergence_criterion,
    equilibrium_intensity,
    equilibrium_intensity_roots,
    price_partition,
    collective_optimum_fraction,
)

# Bistable emergence (main text: "Where monuments appear", "Bistable spread
# and the pattern of independent traditions")
from signaling.emergence import (
    phi_star,
    rare_builder_fitness_advantage,
    replicator_dynamics,
    sigma_star_invasion,
)

# Spatial dynamics: bistable reaction-diffusion (main text: "Bistable spread
# and the pattern of independent traditions")
from signaling.spatial import (
    PDEResult,
    critical_droplet_action,
    critical_nucleus_radius,
    critical_nucleus_radius_allen_cahn,
    critical_nucleus_radius_dimensional_estimate,
    critical_nucleus_radius_pde,
    critical_nucleus_radius_pde_degenerate,
    degenerate_diffusion_table,
    divergence_diffusion_2d,
    nondivergence_diffusion_2d,
    interfacial_tension,
    nucleation_rate_estimate,
    laplacian_2d,
    potential_W,
    pinning_at_discontinuity,
    reaction_integral,
    reaction_term,
    solve_pde_2d,
    solve_pde_2d_degenerate,
    stochastic_lattice_simulation,
    traveling_wave_velocity,
    traveling_wave_velocity_dimensional_estimate,
    traveling_wave_velocity_pde,
)

# Placement prediction (isolated module; SI "Further derived predictions:
# placement, competitive investment, and size inequality")
from signaling.placement import (
    comparative_static,
    optimal_placement,
    placement_payoff,
    resource_cost,
    visibility_between,
    visibility_within,
)

# Competitive investment (decoupled module; SI "Further derived predictions:
# placement, competitive investment, and size inequality")
from signaling.competition import (
    dyadic_asymmetry,
    dyadic_effort,
    dyadic_total,
    regional_investment,
    verify_dyadic_equilibrium,
)

# Size-inequality prediction (isolated module; SI "Further derived
# predictions: placement, competitive investment, and size inequality")
from signaling.size_inequality import (
    gini,
    monument_sizes,
    predicted_size_gini,
)

__all__ = [
    # Layer 1 dataclasses
    "CostSpec",
    "BenefitSpec",
    "SpenceResult",
    "EquilibriumResult",
    "FitnessResult",
    # Layer 1 cost/benefit factories
    "quadratic_cost",
    "power_cost",
    "exponential_cost",
    "linear_benefit",
    "concave_benefit",
    # Layer 1 numerical functions
    "equilibrium_investment",
    "equilibrium_fitness",
    "fitness_gain",
    "cost_at_equilibrium",
    "average_equilibrium_cost",
    "lambda_W_for_C",
    "mean_payoff_multiplier",
    # Layer 1 symbolic functions
    "verify_spence_condition",
    "derive_equilibrium",
    "derive_equilibrium_fitness",
    "derive_aggregate_signal",
    # Layer 1 aggregation
    "group_monument_stock",
    "expected_monument_stock",
    # Layer 1 deviation/pooling analysis
    "receiver_inference",
    "fitness_at_deviation",
    "pooling_fitness",
    "expected_fitness_gain",
    # Layer 1 participation game (free-rider resolution)
    "free_rider_deterrent",
    "participation_equilibrium",
    "participation_differential_sampled",
    # Layer 1 sensitivity
    "cost_function_sensitivity",
    "benefit_function_sensitivity",
    # Channel selection analysis
    "SignalChannel",
    "MONUMENT_CHANNEL",
    "FEAST_CHANNEL",
    "RITUAL_CHANNEL",
    "HUNTING_CHANNEL",
    "VERBAL_CHANNEL",
    "ALL_CHANNELS",
    "lambda_decomposition",
    "channel_effective_lambda",
    "signal_fidelity",
    "channel_dominance_condition",
    "monument_dominance_threshold",
    "incremental_lambda",
    # Layer 2 functions
    "effective_noise",
    "mutual_assessment_conflict_prob",
    "mutual_assessment_exponential",
    "self_assessment_conflict_prob",
    "bourgeois_conflict_prob",
    "war_of_attrition_cost",
    "war_of_attrition_deterrence",
    "derived_conflict_reduction",
    "derived_conflict_reduction_self_assessment",
    "compare_assessment_models",
    "calibrate_conflict_reduction",
    "constrained_sigma_0",
    # Layer 2 calibration defaults
    "DEFAULT_SIGMA_0",
    "DEFAULT_KAPPA",
    "DEFAULT_T_0",
    "DEFAULT_BETA_CONFLICT",
    "DEFAULT_V",
    "DEFAULT_D",
    "DEFAULT_P_BASE",
    "DEFAULT_ALPHA_CONFLICT",
    "DEFAULT_M_THRESH",
    "DEFAULT_M_SCALE",
    "DEFAULT_M_OWN",
    "DEFAULT_STEEPNESS",
    "DEFAULT_C_RATE",
    # Calibration
    "RAPA_NUI",
    "RAPA_ITI",
    "INITIAL_MODEL_PARAMS",
    "CALIBRATION_TARGETS",
    "DEFAULT_LAMBDA",
    "DEFAULT_LAMBDA_W_ANCHOR",
    "DEFAULT_Q_MIN",
    "DEFAULT_Q_MAX",
    "DEFAULT_N",
    "DEFAULT_N_COMPUTE",
    "DEFAULT_LAM_W",
    "DEFAULT_LAM_C",
    "DEFAULT_LAM_X",
    "DEFAULT_RHO_MONUMENT",
    "DEFAULT_RHO_FEAST",
    "DEFAULT_RHO_RITUAL",
    "DEFAULT_RHO_HUNTING",
    "DEFAULT_RHO_VERBAL",
    "DEFAULT_WINDFALL_PROB",
    # Price equation: sensitivity analysis
    "sigma_star_vs_param",
    "sensitivity_tornado",
    # Full multilevel Price partition
    "within_group_status_differential",
    "mixed_group_mean_fitness",
    "within_group_regression",
    "between_group_regression",
    "emergence_criterion",
    "equilibrium_intensity",
    "equilibrium_intensity_roots",
    "price_partition",
    "collective_optimum_fraction",
    "sigma_star_self_consistent",
    "stability_analysis",
    "stability_analysis_self_consistent",
    # Bistable emergence
    "rare_builder_fitness_advantage",
    "sigma_star_invasion",
    "phi_star",
    "replicator_dynamics",
    # Spatial dynamics
    "PDEResult",
    "critical_droplet_action",
    "critical_nucleus_radius",
    "critical_nucleus_radius_allen_cahn",
    "critical_nucleus_radius_dimensional_estimate",
    "critical_nucleus_radius_pde",
    "critical_nucleus_radius_pde_degenerate",
    "degenerate_diffusion_table",
    "divergence_diffusion_2d",
    "nondivergence_diffusion_2d",
    "interfacial_tension",
    "nucleation_rate_estimate",
    "laplacian_2d",
    "potential_W",
    "pinning_at_discontinuity",
    "reaction_integral",
    "reaction_term",
    "solve_pde_2d",
    "solve_pde_2d_degenerate",
    "stochastic_lattice_simulation",
    "traveling_wave_velocity",
    "traveling_wave_velocity_dimensional_estimate",
    "traveling_wave_velocity_pde",
    # Placement prediction (isolated downstream module)
    "PLACEMENT",
    "visibility_between",
    "visibility_within",
    "resource_cost",
    "placement_payoff",
    "optimal_placement",
    "comparative_static",
    # Competitive investment (decoupled module)
    "COMPETITION",
    "dyadic_effort",
    "dyadic_total",
    "dyadic_asymmetry",
    "verify_dyadic_equilibrium",
    "regional_investment",
    # Size-inequality prediction (M1)
    "gini",
    "monument_sizes",
    "predicted_size_gini",
    # Layer 3 alternative network forms (SI "Network degree functional-form robustness")
    "NetworkDegreeSpec",
    "between_group_lambda_diagnostics",
    "calibrate_alternative_network_forms",
    "network_degree_exponential",
    "network_degree_exponential_derivative",
    "network_degree_hill",
    "network_degree_hill_derivative",
    "network_degree_piecewise",
    "network_degree_piecewise_derivative",
]
